module.exports = {
  apps: [
    {
      name: 'growprofile',
      script: '.next/standalone/server.js',
      cwd: '/root/growprofile',
      env_file: '/root/growprofile/.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'webhook-worker',
      script: '/root/growprofile/node_modules/.bin/tsx',
      args: 'lib/workers/webhook-process.worker.ts',
      cwd: '/root/growprofile',
      env_file: '/root/growprofile/.env',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 3000,
    },
    {
      name: 'dm-sender-worker',
      script: '/root/growprofile/node_modules/.bin/tsx',
      args: 'lib/workers/dm-sender.worker.ts',
      cwd: '/root/growprofile',
      env_file: '/root/growprofile/.env',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 3000,
    },
  ],
}
